name: Build web
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install
        run: |
          pnpm install
      # dist/404.html: gh-pages history mode
      - name: Build
        run: |
          npm run build-gh-pages
          cp dist/browser/index.html dist/browser/404.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/browser
